name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose --features unsafe_tests
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run fuzzing
      run: |
        cargo install cargo-fuzz
        cargo fuzz run round_trip -- -runs=100000
        cargo fuzz run escape -- -runs=100000
        cargo fuzz run escape_quoted -- -runs=100000
        cargo fuzz run unescape -- -runs=100000
